const CartActionsTypes = {
  TOOGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOTE_ITEM: "REMOTE_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionsTypes;
